apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: belajar-devops
data:
  PORT: "8080"
  DB_HOST: "belajar-postgres.cc5migaw0e4u.us-east-1.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: "belajardb"
  DB_USER: "appuser"

