apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Backend repo cuma manage deployment + service-nya sendiri.
# Namespace & configmap dimiliki repo frontend (dibuat duluan).
resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - pvc.yaml
  - storageclass.yaml
