apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-data
  namespace: belajar-devops
spec:
  accessModes:
    - ReadWriteOnce          # EBS cuma bisa 1 node
  storageClassName: ebs-gp3
  resources:
    requests:
      storage: 1Gi
